//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_JR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int Id_prod { get; set; }
        public string ProdNombre { get; set; }
        public string ProdDescripcion { get; set; }
        public int Id_cat { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
